### ISSUE TITLE
Input to Future Trajectory Decoder (Ut)

### ISSUE THREAD

**Issue by AndreHenkel** [HarshayuGirase/Human-Path-Prediction#33]
Hi, 
I'm currently using your Y-Net on Simulated Data and it works very well. Thank you for the great code :)

My question regards the input for the Trajectory Decoder (Ut). In your paper it seems, that you use the feature output from the Encoder(Ue) together with the **predicted** goal from the Ug Decoder. But going over your code in "ynet/train.py" in line 83 it seems, that you use the ground-truth information for the goal.
Am I missing something, or are both approaches considered ok?

Best and thank you,

André

**Comment by DeepOzean** [comment]
Hi Andre, 

Great our work helps your research :)

There is a difference between training and inference/testing phase. During training the submodel Ut uses the ground-truth goal. The intuition is that the model should learn that predicting a path towards the conditioning coordinate (i.e. the ground-truth goal) is leading to small errors.

During inference, Ut is conditioned towards the predicted goals (test.py line 159, waypoints include the predicted goal and intermediate waypoints). Since during training it learned that following this coordinate leads to small errors, it will still do that during inference.

Hope that helps.

Best,
Yang

**Comment by AndreHenkel** [comment]
Thank you very much.
It makes sense and I adopted it :)

Best,
André
